### ISSUE TITLE
Add pattern-newcomer.md to the spine/navigation

### ISSUE THREAD

**Issue by skreutzer** [Peeragogy/Peeragogy.github.io#12]
$/pattern-newcomer.md is omitted in $/_layouts/default.html (the main template for Jekyll of GitHub Pages, which generates the $/_site/*.html files that go live on peeragogy.github.io).

There's the option to update default.html manually, but doing so is error-prone and likely the root cause for this omission in the first place. Using GitHub Pages for "serverless" simply means becoming dependent on GitHub's/Microsoft's server, where there's no chance for server-side scripting (Jekyll or general purpose programming). The Jekyll templating engine for GitHub Pages on the GitHub server would already need to provide a way to generate the spine/navigation automatically from the content of the repository, for which it is unknown if such a function exists. If it doesn't, there would be the option to install Jekyll (based on Ruby) locally, but then, why bother with a package that comes with its own package manager (capability infrastructure versus system in a system) instead of packaging for ordinary distro repositories, and why prefer Jekyll templates if it could also be XML/XSLT? Subsequently, new client code could analyze the repository to detect all $/*md (Markdown) files, filter out the special ones, then generate an index file in, for example, the Open Packaging Format (an open standard by the IDPF or W3C now for exactly this purpose, also incorporated into the open EPUB standard for packaging, transferring, archiving electronic publications). The result of this latter step could be checked in into the repository, so that a current version comes out of the box, and a newly generated version could with some code compare if there are new/removed entries that aren't reflected in the spine/navigation, so it gets easy to decide if the change of a Markdown file should be added to the filter or the new index file should simply be checked in. This most recent index file could then be used as basis to generate a spine/navigation file, probably as a separate Navigation Control File (NCX, by the DAISY Consortium Digital Talking Book standard) or analogous to the OPF spine (integrated or separate), again being checked in as well for comparison reasons. There could be several of such paths/sequences through the content maintained, which would also solve the frequent question if/how different variants/compositions of the handbook could be offered for different audiences and use cases. Ideally, these steps would be managed by a GUI, especially to help with rearranging and updating the spine/navigation files if there should be many of them, and for each new file, it would be necessary to decide to which compilations and where these should be added, and to warn/notify for removed files. With all of this in place, a page generator template could automatically add all navigational interlinking between pages for all spines/paths, and a second template step could then apply a particular layout, for all target formats the handbook needs to be made available in. There are certainly many abbreviations to arrive at the same result, for example with a little bit of static scripting/coding, but the proposed workflow here suggests a semantic + capability-oriented approach.

For this issue, it's up to decide whether to just quickly change the $/_layouts/default.html manually or otherwise start a potentially large software development project (in the hope that it'll be of general use for other similar content projects - especially if those already benefit from proper semantic packaging files being already in place, not being based on some Markdown + GitHub Jekyll).

**Comment by holtzermann17** [comment]
I think we should just fix the missing link for now and move most of this to a new issue. I remember when I set up the Jekyll site being annoyed that I couldn’t do any scripting. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by skreutzer** [comment]
As it turned out, there are apparently two sources for spine definition:

- grep of links in $/index.html updates the LaTeX files from the Markdown source
- $/en/peeragogy-shell.tex of the peeragogy-handbook repository defines what gets included in the PDF

Therefore, this seems to be the currently accepted approach defining the spine, the index.html with grep being primary and the peeragogy-shell.tex only secondary. Other target formats (like the e-book) may use this source and the same approach to determine which material needs to be included. It also allows multiple spine definitions to be created which include different material, of which all variants/packages get automatically generated. For the latter, it's not really useful to define the list of links in a similar way like the $/index.html does for the GitHub Pages Jekyll page of the Peeragogy Project for the Web, but instead, it should better be a valid, well-formed XHTML file containing these links for grep, not cluttered with any extra Web stuff.

$/_layouts/default.html seems to be irrelevant for defining the inclusion of material, it's merely a template for the GitHub Pages website via Jekyll adding navigational links based on a list of recognized source files (not generated nor automatically updated).

This issue is about adding $/pattern-newcomer.md to the navigation of the website, which relies on $/_layouts/default.html. Said file should be automatically generated (by Jekyll or locally in a repository together with subsequent checkin?) from the $/index.html + grep + whatever additionally is needed.
