### ISSUE TITLE
When will v3 be available on amazon?

### ISSUE THREAD

**Issue by holtzermann17** [Peeragogy/Peeragogy.github.io#7]
I'm curious and readers may be interested as well, has a launch date been confirmed for the amazon edition of v3?

@danoff @daytripper

**Comment by skreutzer** [comment]
Can be closed because https://www.amazon.com/Peeragogy-Handbook-V-No-Longer-Missing-Production/dp/0996097511/

**Comment by daytripper** [comment]
So nice to have more eyes on the prize! Thanks again.
