### ISSUE TITLE
QuickStart guide is out of date

### ISSUE THREAD

**Issue by holtzermann17** [Peeragogy/Peeragogy.github.io#9]
The Quickstart guide mentions Google+ and has some other outdated aspects compared with current practices in our project. It should be updated to match. There’s also a version on the wiki so we could use the wiki to work out what to say in the current Quickstart guide.

Someone commented as well that this Quickstart guide explains how to join our project but it doesn’t explain how to Quickstart yourself in a new peer learning or peer production project. So we should probably add some helpful information for people who want to start their own projects. Or who want to dive into other peoples projects besides the one that we have here.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by skreutzer** [comment]
Note: the Quickstart guide isn't in the wiki of this repository, but instead belongs to the GitHub wiki website of the Handbook repository: https://github.com/Peeragogy/peeragogy-handbook/wiki/Quickstart-guide

**Comment by holtzermann17** [comment]
We have updated the text of the Micro Quickstart and first section of the Quickstart guide.  I think this issue itself can close. However, what's needed as a next step is a thorough revision of the "Onboarding" project as a decomposition into tickets.  That can be based on a further detailed reading of the Quickstart guide (linked above).
